 **** -->lab2  Connection of github and Kaggle 

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print("a:\n", a)

a:
 [1 2 3]


In [3]:
a1 = np.array([1, 2, 3])
print("a1: \n", a1)

print("\nNumber of axes/dimensions in the array: ", a1.ndim)
print("Shape of the array: ", a1.shape)
print("Size of the array/Number of Elements in the: ", a1.size)
print("Type of the elements in the array: ", a1.dtype)
print("Size of the elements in the array: ", a1.itemsize)
print("Buffer containing the array: ", a1.data)

a1: 
 [1 2 3]

Number of axes/dimensions in the array:  1
Shape of the array:  (3,)
Size of the array/Number of Elements in the:  3
Type of the elements in the array:  int64
Size of the elements in the array:  8
Buffer containing the array:  <memory at 0x7be091537dc0>


**1) creating one dimensions array from list**

In [4]:
array =np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


**2) to create a 3x3 matrix with values ranging from2 to 10**

In [5]:
array =np.array([[2,3,4],[5,6,7],[8,9,10]])
print(array)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


 **3) to append values at the end of an array**

In [6]:
array = np.array([1,2,3,4,5])
print(array)
array = np.append(array,[6,7,8])
print(array)

[1 2 3 4 5]
[1 2 3 4 5 6 7 8]


**4) to create another shape from an array without changing its data (3x2 to    2x3)**

In [7]:
array = np.array([[1,2,3],[4,5,6]])
print("Matrix is 3x2 \n",array)
array = np.array([[1,2],[3,4],[5,6]])
print("Matrix is 2x3 \n",array)

Matrix is 3x2 
 [[1 2 3]
 [4 5 6]]
Matrix is 2x3 
 [[1 2]
 [3 4]
 [5 6]]
